# Generated by Django 6.0.2 on 2026-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=150, verbose_name='Full Name'),
        ),
    ]
